declare const LogarithmicTypeScale: {
  u18: string;
  u17: string;
  u16: string;
  u15: string;
  u14: string;
  u13: string;
  u12: string;
  u11: string;
  u10: string;
  u9: string;
  u8: string;
  u7: string;
  u6: string;
  u5: string;
  u4: string;
  u3: string;
  u2: string;
  u1: string;
  d1: string;
  d2: string;
  d3: string;
  d4: string;
  d5: string;
  d6: string;
  d7: string;
  d8: string;
  d9: string;
  d10: string;
  d11: string;
  d12: string;
  d13: string;
  d14: string;
  d15: string;
  d16: string;
  d17: string;
  d18: string;
};

export default LogarithmicTypeScale;
