export declare const defaultScale: {
    u18: string;
    u17: string;
    u16: string;
    u15: string;
    u14: string;
    u13: string;
    u12: string;
    u11: string;
    u10: string;
    u9: string;
    u8: string;
    u7: string;
    u6: string;
    u5: string;
    u4: string;
    u3: string;
    u2: string;
    u1: string;
    d1: string;
    d2: string;
    d3: string;
    d4: string;
    d5: string;
    d6: string;
    d7: string;
    d8: string;
    d9: string;
    d10: string;
    d11: string;
    d12: string;
    d13: string;
    d14: string;
    d15: string;
    d16: string;
    d17: string;
    d18: string;
    u18r: string;
    u17r: string;
    u16r: string;
    u15r: string;
    u14r: string;
    u13r: string;
    u12r: string;
    u11r: string;
    u10r: string;
    u9r: string;
    u8r: string;
    u7r: string;
    u6r: string;
    u5r: string;
    u4r: string;
    u3r: string;
    u2r: string;
    u1r: string;
    d1r: string;
    d2r: string;
    d3r: string;
    d4r: string;
    d5r: string;
    d6r: string;
    d7r: string;
    d8r: string;
    d9r: string;
    d10r: string;
    d11r: string;
    d12r: string;
    d13r: string;
    d14r: string;
    d15r: string;
    d16r: string;
    d17r: string;
    d18r: string;
};
export declare class Scale {
    factor: number;
    delta: number;
    constructor({ factor, delta }: {
        factor: number;
        delta: number;
    });
    /** Return change in scale, in ems */
    scale(n: number, options?: {
        root?: boolean;
    }): string;
}
